name: 'Crash Report'
description: 'Report a crash'
title: '[Crash]: '
body:
  - type: 'markdown'
    attributes:
      value: 'Before reporting this crash, have you tried the following?

        - Updating to the latest version of the modpack

        - Removed any additional mods you may have installed

        '
  - type: 'dropdown'
    id: 'triedFixes'
    attributes:
      label: 'Suggested fixes'
      description: 'Have you tried the suggested fixes above?'
      options:
        - null
        - 'Yes'
    validations:
      required: true
  - type: 'dropdown'
    id: 'ftb-modpack-dropdown'
    attributes:
      label: 'Modpack'
      description: 'Which modpack are you having the crash on?'
      options:
        - 'FTB Presents Direwolf20 1.21'
        - 'FTB Evolution'
        - 'FTB Unstable 1.21'
        - 'FTB NeoTech'
        - 'FTB Builders Paradise 2'
        - 'FTB Presents F.A.M'
        - 'FTB Genesis'
        - 'FTB Presents Direwolf20 1.20'
        - 'FTB Skies Expert'
        - 'FTB Arcanum Institute'
        - 'FTB Presents AbePack'
        - 'FTB Interactions Remastered'
        - 'FTB Unstable 1.20: Forge'
        - 'FTB Unstable 1.20: Fabric'
        - 'FTB University 1.19'
        - 'FTB Presents Integration by Parts DX'
        - 'FTB Skies'
        - 'FTB Legend of the Eyes'
        - 'FTB Presents Direwolf20 1.19'
        - 'FTB StoneBlock 3'
        - 'FTB Inferno'
        - 'FTB One'
        - 'FTB Plexiglass Mountain'
        - 'FTB Presents Direwolf20 1.18'
        - 'FTB Chocolate'
        - 'FTB Ultimate: Anniversary Edition'
        - 'FTB OceanBlock'
        - 'FTB University 1.16'
        - 'FTB Academy 1.16'
        - 'FTB Cotton'
        - 'FTB Endeavour'
        - 'FTB Presents Direwolf20 1.16'
        - 'FTB Mage Quest'
        - 'YogCraft Modpack'
        - 'FTB Ultimate'
        - 'FTB Tech World'
        - 'MindCrack Pack'
        - 'Magic World'
        - 'FTB Lite 2'
        - 'Direwolf20 1.4.7'
        - 'FTB Monster'
        - 'FTB Horizons'
        - 'FTB Presents Direwolf20 - 1.6.4'
        - 'FTB Magic World 2'
        - 'FTB Tech World 2'
        - 'Slow''s Stream Pack'
        - 'Pax East 2014 Map'
        - 'FTB Lite'
        - 'FTB Pax Challenge Pack 2013'
        - 'FTB University 1.12'
        - 'FTB Unstable 1.16'
        - 'FTB Builders Paradise'
        - 'FTB Ultimate Reloaded'
        - 'FTB Revelation'
        - 'FTB Continuum'
        - 'FTB Sky Adventures'
        - 'FTB Pyramid Reborn 3.0'
        - 'FTB Presents Direwolf20 1.12'
        - 'FTB Unstable 1.12'
        - 'FTB Horizons III'
        - 'FTB Beyond'
        - 'FTB Egg Hunt'
        - 'FTB SkyFactory Challenges'
        - 'FTB Presents Skyfactory 3'
        - 'FTB Presents Direwolf20 1.10'
        - 'FTB Infinity Evolved 1.7'
        - 'FTB Presents Crackpack'
        - 'FTB Inventions'
        - 'FTB Infinity Evolved Skyblock'
        - 'FTB Presents Skyfactory 2.5'
        - 'FTB Vanilla+'
        - 'FTB Horizons: Daybreaker'
        - 'FTB Departed'
        - 'FTB Presents Cloud 9'
        - 'FTB Presents Direwolf20'
        - 'FTB Trident'
        - 'FTB Resurrection'
        - 'FTB Lite 3'
        - 'Pax Prime 2015 Map'
        - 'FTB Presents HermitPack'
        - 'FTB Sky Odyssey'
        - 'FTB Unstable 1.14'
        - 'FTB Omnia'
        - 'FTB Interactions'
        - 'FTB Presents Stoneblock 2'
        - 'FTB Academy 1.12'
        - 'Other...'
    validations:
      required: true
  - type: 'input'
    id: 'modpackVersion'
    attributes:
      label: 'Modpack Version'
      description: 'Which modpack version are you having the issue on?'
      placeholder: 'ex. 1.7.0'
    validations:
      required: true
  - type: 'textarea'
    id: 'description'
    attributes:
      label: 'Describe what happened'
      description: 'Describe what you were doing in the moments leading up to the
        crash, be as detailed as possible and include steps on how to reproduce
        the crash.'
    validations:
      required: true
  - type: 'input'
    id: 'crashreport'
    attributes:
      label: 'Crash Report'
      description: 'Upload your crash report to https://gist.github.com/ and put the
        link in here, [Finding the crash
        report](https://docs.feed-the-beast.com/docs/app/Instances/instance-logs#locating-crashlogs)'
      placeholder: 'https://gist.github.com/'
    validations:
      required: true
  - type: 'input'
    id: 'debuglog'
    attributes:
      label: 'Debug Log'
      description: 'Upload your debug.log to https://gist.github.com/ and put the link
        in here, [Finding the crash
        report](https://docs.feed-the-beast.com/docs/app/Instances/instance-logs)'
      placeholder: 'https://gist.github.com/'
  - type: 'markdown'
    attributes:
      value: 'This template was generated with [Issue Forms
        Creator](https://issue-forms-creator.netlify.app)'
