name: Crash Report
description: Use this form if you are running into any crashes or disconnects
labels:
  - Bug
  - 'type: Crash/Disconnect'
body:
  - type: markdown
    attributes:
      value: >-
        ## Before continuing, please make sure you have tried the following:


        - Updating the pack to the latest available version

        - If you have added/removed any mods, either undo the changes or install
        a second unmodified copy of the modpack
  - type: dropdown
    id: triedSolutions
    attributes:
      label: 'Have you tried the solutions mentioned above? '
      options:
        - 'No'
        - 'Yes'
    validations:
      required: true
  - type: dropdown
    id: ftb-modpack-dropdown
    attributes:
      label: Modpack
      description: What modpack are you having an issue with?
      options:
        - Other
    validations:
      required: true
  - type: input
    id: modpack-version
    attributes:
      label: Modpack Version
      description: The modpack version can often be found on the launcher you are using
      placeholder: e.g. 1.1.5
    validations:
      required: true
  - type: textarea
    id: bug-desc
    attributes:
      label: Describe what happened
      description: >-
        A clear and concise description of what the bug is along with any
        screenshots that can help explain the issue
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Link to logs
      description: >-
        Please upload your logs to a pastebin service such as
        [Gist](https://gist.github.com/), [mclo.gs](https://mclo.gs/) and link
        them here. If you are not sure which logs to upload, please upload the
        debug.log file from the modpack folder.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: >-
        If you are able to reproduce the issue, please provide a step by step
        guide on how we can try and reproduce the issue.
      placeholder: '1. Go to ...

        2. Click on ...

        3. Scroll down to ...

        4. See error'
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: >-
        Any other information that may help debug the issue. If you have        
        modified the modpack please let us know what was changed here
      placeholder: >-
        Any other information that may help debug the issue. If you have        
        modified the modpack please let us know what was changed here