name: 'Suggestion'
description: 'Suggestion'
type: 'Feature'
body:
  - type: 'dropdown'
    id: 'ftb-modpack-dropdown'
    attributes:
      label: 'Modpack'
      description: 'What modpack is your suggestion for?'
      multiple: false
      options:
        - 'FTB Unstable 6'
        - 'FTB StoneBlock 4'
        - 'FTB Skies 2'
        - 'FTB OceanBlock 2'
        - 'FTB Presents Direwolf20 1.21'
        - 'FTB Evolution'
        - 'FTB NeoTech'
        - 'FTB Builders Paradise 2'
        - 'FTB Skies Expert'
        - 'FTB Arcanum Institute'
        - 'FTB Interactions Remastered'
        - 'FTB Skies'
        - 'FTB StoneBlock 3'
        - 'Other...'
    validations:
      required: true
  - type: 'textarea'
    id: 'problem'
    attributes:
      label: 'Is your suggestion related to a problem? Please describe.'
      description: 'A clear and concise description of what the problem is.'
      placeholder: 'Ex. I''m always frustrated when [...]'
  - type: 'textarea'
    id: 'mod'
    attributes:
      label: 'Mod suggestion'
      description: 'Link to mod and describe why you would like to see the mod in the pack?'
      placeholder: 'Link to mod:

        A clear and concise description of what the mod what add and why you
        would like it in the pack.

        '
