name: Suggestion
description: Suggestion
body:
  - type: dropdown
    id: ftb-modpack-dropdown
    attributes:
      label: Modpack
      description: What modpack is your suggestion for?
      multiple: false
      options:
        - FTB Skies
        - FTB Legend of the Eyes
        - FTB Presents Direwolf20 1.19
        - FTB StoneBlock 3
        - FTB Inferno
        - FTB One
        - FTB Plexiglass Mountain
        - FTB Presents Direwolf20 1.18
        - FTB Chocolate
        - "FTB Ultimate: Anniversary Edition"
        - FTB OceanBlock
        - FTB University 1.16
        - FTB Academy 1.16
        - FTB Cotton
        - FTB Endeavour
        - FTB Presents Direwolf20 1.16
        - FTB Mage Quest
        - YogCraft Modpack
        - FTB Ultimate
        - FTB Tech World
        - MindCrack Pack
        - Magic World
        - FTB Lite 2
        - Direwolf20 1.4.7
        - FTB Monster
        - FTB Horizons
        - FTB Presents Direwolf20 - 1.6.4
        - FTB Magic World 2
        - FTB Tech World 2
        - Slow's Stream Pack
        - Pax East 2014 Map
        - FTB Lite
        - FTB Pax Challenge Pack 2013
        - FTB University 1.12
        - FTB Unstable 1.16
        - FTB Builders Paradise
        - FTB Ultimate Reloaded
        - FTB Revelation
        - FTB Continuum
        - FTB Sky Adventures
        - FTB Pyramid Reborn 3.0
        - FTB Presents Direwolf20 1.12
        - FTB Unstable 1.12
        - FTB Horizons III
        - FTB Beyond
        - FTB Egg Hunt
        - FTB SkyFactory Challenges
        - FTB Presents Skyfactory 3
        - FTB Presents Direwolf20 1.10
        - FTB Infinity Evolved 1.7
        - FTB Presents Crackpack
        - FTB Inventions
        - FTB Infinity Evolved Skyblock
        - FTB Presents Skyfactory 2.5
        - FTB Vanilla+
        - "FTB Horizons: Daybreaker"
        - FTB Departed
        - FTB Presents Cloud 9
        - FTB Presents Direwolf20
        - FTB Trident
        - FTB Resurrection
        - FTB Lite 3
        - Pax Prime 2015 Map
        - FTB Presents HermitPack
        - FTB Sky Odyssey
        - FTB Unstable 1.14
        - FTB Omnia
        - FTB Interactions
        - FTB Presents Stoneblock 2
        - FTB Academy 1.12
        - Other...
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your suggestion related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]
  - type: textarea
    id: mod
    attributes:
      label: Mod suggestion
      description: Link to mod and describe why you would like to see the mod in the pack?
      placeholder: >
        Link to mod:

        A clear and concise description of what the mod what add and why you would like it in the pack.
