name: 'Close idle mod related issues'
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: '@Gaz492 @Saereth Please check if the mod has recieved an update, if there has been no mod updates this issue will close in 24 hours'
          close-issue-message: 'Closing issue as there has been no activity'
          days-before-stale: 59
          days-before-close: 1
          days-before-pr-close: -1
          stale-issue-label: 'state: Stale'
          any-of-issue-labels: 'state: Reported to Mod Dev, state: Awaiting Mod Update'
          exempt-issue-labels: 'state: Mod Update Available,In Progress'
          operations-per-run: 200
          ignore-issue-updates: true
