name: 'Close stale issues (Mod issue label)'
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: '@Gaz492 @Saereth Please check if the mod has recieved an update'
          close-issue-message: 'This issue has been closed as the mod author has not released an update that fixes this issue'
          days-before-stale: 29
          days-before-close: 1
          days-before-pr-close: -1
          stale-issue-label: 'state: Stale'
          only-issue-labels: 'state: Reported to Mod Dev, state: Awaiting Mod Update'
          exempt-issue-labels: 'state: Mod Update Available'
          operations-per-run: 100
