name: 'Close stale issues and PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue has been marked as stale. Please reply to the issue or the issue will be automatically closed in 3 days.'
          close-issue-message: 'This issue has been closed as there has been no recent activity after being marked as stale.'
          days-before-stale: 7
          days-before-close: 3
          days-before-pr-close: -1
          stale-issue-label: 'state: Stale'
          only-issue-labels: 'state: Awaiting Reply'
          operations-per-run: 100
