name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'Message to comment on stale issues. If none provided, will not mark issues stale'
          close-issue-message: 'This issue / Pull request has been closed as there has been no recent activity after being marked as stale.'
          days-before-stale: 7
          days-before-close: 3
          days-before-pr-close: -1
          only-issue-labels: 'state: Awaiting Reply'
